### ISSUE TITLE
Unreleased documents

### ISSUE THREAD

**Issue by StuartHarris** [MHRA/products#48]
Document metadata has a field showing the "release state". Either we should import released documents only, or we should filter out unreleased documents on all searches.

**Comment by m-doughty** [comment]
So my thoughts re: this are that we either need to not import or not index when release state isn't `Y`. Whilst we could filter on search, the problem is that anyone with access to the network tab can just modify the search string and find unreleased documents.

**Comment by m-doughty** [comment]
I've taken a deep dive into this and it looks like conditional indexing *isn't* a thing, but conditional transformations are. We're left with the following feasible options:

1. Don't import the files which aren't `release_state=Y` in the first place;
2. Use the Conditional skill to delete the path to the PDF & other sensitive metadata (or encrypt it with a key we don't expose to the client) when we run the indexer.

This is a short term concern because when we implement the API, the Azure API search key can be kept private and we can pre-filter the index API-side.

Thoughts @MHRA/products-dev?
