### ISSUE TITLE
Cookies don't clear on Edge

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#553]
**Describe the bug**
Analytics cookies don't clear on Edge.

**To Reproduce**
1. Accept cookies.
2. Clear cookies.
3. Observe that cookies not cleared in developer tools window.

**Expected behavior**
All cookies are cleared.

**Screenshots**
N/A

**Additional context**
The cookie domain identified by all other browsers is ".windows.net". This has to be specified at the time of clearing. Edge identifies the domain as "windows.net" (no proceeding ".") so the cookies are not cleared.

**Comment by m-doughty** [comment]
@TimboTambo Just for context, is this referring to Edge Legacy (IE-based) or Edge (Chromium-based)?

**Comment by m-doughty** [comment]
**Tested on:** 

- Edge (Chromium-based)
- Edge Legacy
- Google Chrome on Windows 10.

**Actions taken:**

1. Navigated to https://products.mhra.gov.uk
2. Navigated to the Cookie Policy page;
3. Switched Google Analytics Cookies to Off;
4. Clicked 'Save your preferences'.

**Expected behavior:**

1. No more traffic will be sent to Google Analytics. :ok_hand: 
2. Cookies `_ga`, `_gid`, and `_gat*` will be removed. :no_entry_sign: 

I couldn't find any Edge-specific behavior here other than Edge Legacy displaying the `mhra.gov.uk` domain rather than the `.mhra.gov.uk` domain -- I'm dubious as to whether this is a difference internally or just a display difference. 

What appears to be happening is that the cookies _are_ being cleared (on all browsers), but are being re-created as soon as the page reloads. However, once cookies are disabled, I can't see any further traffic being sent to Google Analytics.

**Comment by craiga** [comment]
Sorry @m-doughty , I just noticed this ticket is missing a bit of context which would've been helpful :(

It comes from [this report](https://github.com/MHRA/products/issues/498#issuecomment-603241619) from @AndySnowMHRA.

**Comment by m-doughty** [comment]
After meeting with @craiga, it seems that after whichever changes were pushed most recently, this now correctly clears cookies and ceases to send analytics requests on latest versions of:

- Chrome;
- Edge;
- Edge Legacy.

@AndySnowMHRA Can you confirm if you're still seeing any issues?

**Comment by TimboTambo** [comment]
@m-doughty Can confirm that I can't recreate this issue in production either. Might have been something specific to the staging environment, where the bug was identified. @AndySnowMHRA if you confirm then we can close this issue.

**Comment by m-doughty** [comment]
Have messaged @AndySnowMHRA with our findings, will close the issue if he confirms it's working.

**Comment by AndySnowMHRA** [comment]
> Have messaged @AndySnowMHRA with our findings, will close the issue if he confirms it's working.

Confirmed this is now working correctly on the live site using Edge. 

Ticket can be closed as resolved.

**Comment by m-doughty** [comment]
Resolved!
