### ISSUE TITLE
Fuzzy search not working as expected

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#558]
**Describe the bug**
Mispelled words are not bringing up the correct search results, indicating there may have been some regression of the fuzzy search feature.

**To Reproduce**
1. Search for "paracetanol"
2. Observe no results, where results for "paracetamol" would be expected

**Expected behavior**
Results should be returned for slight variations of the word, to allow for mispelling

**Testing instructions**
1. Search for a mispelling of a product, e.g. "paracetanol". 
2. Observe results for the expected product
3. Go to the live site: [products.mhra.gov.uk](https://products.mhra.gov.uk) and perform the same search for a mispelled product - next to no results should be returned (current behaviour this is fixing).

**Screenshots**
N/A

**Additional context**
This bug may have been introduced in the switch from searchMode "any" -> "all"

**Comment by rjkerrison** [comment]
Agree that this is probably due to the searchMode change. We take all keywords and add them to the search parameters twice, once as `paracetamol~1` and again as `paracetamol^4`. Previously, this weighted exact matches above fuzzy matches. Now it requires something matches both the exact match and the fuzzy match.

**Comment by m-doughty** [comment]
**QA Passed.**

This works as expected, a search for a misspelled substance name brings up results for the correctly spelled substance name again.
