### ISSUE TITLE
Product names saved as string array

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#643]
**Product names saved as string array**
The Document Index Updater is processing product names and saving them in the format `["Product name"]` so that the search results titles display exactly like this on the website.

They should instead display as `Product name`.

**To Reproduce**
1. Go to the nonprod website
2. Perform a search for e.g. `PL 20636/3229`
3. Observe product title in above format, e.g. `["COSOPT PRESERVATIVE-FREE 20 MG/ML + 5 MG/ML EYE DROPS SOLUTION SINGLE DOSE CONTAINER"]`

**Expected behavior**
In above example, product title should display as `COSOPT PRESERVATIVE-FREE 20 MG/ML + 5 MG/ML EYE DROPS SOLUTION SINGLE DOSE CONTAINER`

**Screenshots**
![Screenshot 2020-04-09 at 11 21 03](https://user-images.githubusercontent.com/6436551/78885750-07ce7080-7a55-11ea-9f18-482e1938207f.png)

**Additional context**
This can either be fixed in the processing code or in the definition of the search indexer, to control the way the string is brought across from storage (converting from `["product name"]` to `product name`).

**Comment by m-doughty** [comment]
**QA Comments**

This fix will technically improve the display, but I don't think it actually fixes the underlying problem, which is the Indexer definition [isn't set up to treat this as a collection](https://github.com/MHRA/products/blob/master/medicines/search/definitions/indexers/default.json) (and neither is the front end).

Let's say we have an SPC which relates to Acme Inc Paracetamol, ZTech Headache Relief, and Pharma Inc Paracetamol. The data we have is `["Acme Inc Paracetamol", "ZTech Headache Relief", 
 "Pharma Inc Paracetamol"]` but we're converting this to `Acme Inc Paracetamol, ZTech Headache Relief, Pharma Inc Paracetamol` when we index it.

A user comes along looking for information about `Pharma Inc Paracetamol`. She clicks `P` for the substance list, then `Paracetamol 500mg`, then scrolls the list down to `P`, but the document isn't there because it thinks its product is `Acme Inc Paracetamol, ZTech Headache Relief, Pharma Inc Paracetamol`. We've essentially created information loss.

This also creates [a harder experience generally navigating by product](https://products.mhra.gov.uk/substance/?query=PARACETAMOL), because the user might see:

```
Acme Inc Paracetamol (1 document)
Acme Inc Paracetamol, Pharma Inc Paracetamol (1 document)
Acme Inc Paracetamol, ZTech Headache Relief (1 document)
Acme Inc Paracetamol, Pharma Inc Paracetamol, ZTech Headache Relief (1 document)
Acme Inc Paracetamol, ZTech Headache Relief, Pharma Inc Paracetamol (1 document)
...
Pharma Inc Paracetamol (1 document)
...
```

My thoughts are that we should instead revert this change, define a collection on the indexer and in the index, and be able to display each product independently with all of the documents related to it:

```
Acme Inc Paracetamol (5 documents)
...
Pharma Inc Paracetamol (4 documents)
...
ZTech Headache Relief (3 documents)
```

I'm not sure how much work this would require on the front end. My thoughts are that it's not as simple as it should be (I've been burned by Azure Search collections before), so I'd be happy to approve this as an improvement on what we have and raise a separate user story to really improve the UI. Thoughts @TimboTambo?

**Comment by TimboTambo** [comment]
Yeah agree it'd be better to retain them as a collection and prevent information loss - this PR neither introduces any new problems or fixes any old ones - just fixes the visual bug that was introduced by the doc-index-updater. It would require a bit of work around facet creation and processing (multiple facets per entry) but would likely be worth doing - I suggest creating a ticket for this that we can discuss and prioritise at the next backlog meeting.
