### ISSUE TITLE
Rename SFTP-related env vars to make more generic

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#664]
## User want

As a developer
I want to understand the meaning of environment variables
So that I can understand what they're for clearly, without having to look at the code, to avoid confusion and save me time

## Acceptance Criteria

Environment variables renamed in `products` and `deployments` repo to remove the word `sentinel` - this includes the following existing vars:
- SENTINEL_PUB_KEY_PATH
- SENTINEL_PRIVATE_KEY_PASSWORD
- SENTINEL_PRIVATE_KEY_PATH
- SENTINEL_SFTP_SERVER
- SENTINEL_SFTP_USERNAME

### Customer acceptance criteria

- [ ] _What the customer can check_

### Technical acceptance criteria

- [ ] _Technical things that have to happen_

### Data acceptance criteria

- [ ] _Data that needs to be collected_

### Testing acceptance criteria

- [ ] _Tests or testing enabling changes that need to be made_

## Data - Potential impact

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
@TimboTambo I know I just raised that the names are confusing, however they were given the `SENTINEL_` prefix when we introduced the `Source` enum, so that the `SENTINEL_*` environment variables are associated with the `Sentinel` source. When we include PARs from a different source, or ultimately SPCs and PILs from a different source, we may want that distinction.

**Comment by rjkerrison** [comment]
See here: https://github.com/MHRA/products/pull/484#discussion_r390262750

**Comment by TimboTambo** [comment]
Yeah - good point. Will close this issue.
